require("fany.fanykeymaps")
require("fany.fanytelescope")
require("fany.fanyconfig")
require("fany.fanyformat")
require("fany.utils.fanyutils").set_os_info()
require("fany.fanysnippets")
require("fany.fanyneotree")
require("fany.fanytoggleterm")
